#!/usr/bin/env node
/**
 * The Homebrew cask for a release's Walnut.app (.github/workflows/mac-app.yml
 * attaches it to the release as walnut.rb, next to Walnut.dmg; the tap
 * EvanZhang008/homebrew-tap mirrors the newest one into Casks/):
 *
 *   brew install --cask evanzhang008/tap/walnut
 *
 *   node scripts/homebrew/cask.mjs --version 0.6.7 --sha256 <sha of Walnut.dmg> [--base-url <url>] > walnut.rb
 *
 * The app is a small signed shell: its first launch installs the release's
 * self-contained Walnut into ~/.local/share/open-walnut, which then updates
 * itself, so the cask never needs `auto_updates`. `zap` removes only what the app
 * itself writes under ~/Library; the user's data (~/.open-walnut) and the runtime
 * a `curl | sh` install shares are left alone.
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { REPO_URL } from './formula.mjs'

/** desktop/build-release.sh's CFBundleIdentifier: where macOS keeps the app's own files. */
export const BUNDLE_ID = 'com.local.walnut-desktop'

export function cask({ version, sha256, baseUrl = `${REPO_URL}/releases/download` }) {
  if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`${version} is not a stable version (x.y.z)`)
  if (!/^[0-9a-f]{64}$/.test(sha256)) throw new Error(`${sha256} is not a sha256`)
  return `# Generated by scripts/homebrew/cask.mjs in ${REPO_URL} for Walnut ${version}.
cask "walnut" do
  version "${version}"
  sha256 "${sha256}"

  url "${baseUrl}/v#{version}/Walnut.dmg"
  name "Walnut"
  desc "Personal AI: tasks, notes and Claude Code sessions on your own machine"
  homepage "${REPO_URL}"

  depends_on macos: :monterey

  app "Walnut.app"

  zap trash: [
    "~/Library/Application Support/Walnut",
    "~/Library/Caches/${BUNDLE_ID}",
    "~/Library/HTTPStorages/${BUNDLE_ID}",
    "~/Library/Preferences/${BUNDLE_ID}.plist",
    "~/Library/Saved Application State/${BUNDLE_ID}.savedState",
    "~/Library/WebKit/${BUNDLE_ID}",
  ]

  caveats <<~EOS
    The first launch downloads Walnut itself (about 300 MB) into ~/.local/share/open-walnut;
    it keeps itself up to date from then on. Its sessions run Claude Code:
      https://claude.com/product/claude-code
  EOS
end
`
}

function main(argv) {
  const opts = { version: null, sha256: null, baseUrl: undefined }
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--version') opts.version = argv[++i]
    else if (argv[i] === '--sha256') opts.sha256 = argv[++i]
    else if (argv[i] === '--base-url') opts.baseUrl = argv[++i]
    else throw new Error(`unknown argument ${argv[i]}`)
  }
  if (!opts.version || !opts.sha256) throw new Error('usage: cask.mjs --version <x.y.z> --sha256 <sha of Walnut.dmg> [--base-url <url>]')
  process.stdout.write(cask(opts))
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main(process.argv.slice(2))
  } catch (err) {
    process.stderr.write(`cask: ${err instanceof Error ? err.message : String(err)}\n`)
    process.exit(1)
  }
}
