#!/usr/bin/env node
/**
 * The Homebrew cask for a release's Walnut.app (.github/workflows/mac-app.yml
 * attaches it to the release as walnut.rb, next to Walnut-arm64.dmg and
 * Walnut-x64.dmg; the tap EvanZhang008/homebrew-tap mirrors the newest one into Casks/):
 *
 *   brew install --cask evanzhang008/tap/walnut
 *
 *   node scripts/homebrew/cask.mjs --version 0.7.0 --sha256-arm64 <sha> --sha256-x64 <sha> [--base-url <url>] > walnut.rb
 *
 * Homebrew picks the DMG for the Mac it runs on. The app carries that
 * release's Walnut for its architecture: its first launch installs it into
 * ~/.local/share/open-walnut with no download, and that copy then updates
 * itself, so the cask never needs `auto_updates`. `zap` removes only what the app
 * itself writes under ~/Library; the user's data (~/.open-walnut) and the runtime
 * a `curl | sh` install shares are left alone.
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { REPO_URL } from './formula.mjs'

/** desktop/build-release.sh's CFBundleIdentifier: where macOS keeps the app's own files. */
export const BUNDLE_ID = 'com.local.walnut-desktop'

/** The DMG for each Mac architecture, by Homebrew's name for it and install.sh's. */
export const DMG_ARCHES = [{ brew: 'arm', arch: 'arm64' }, { brew: 'intel', arch: 'x64' }]
export const dmgName = (arch) => `Walnut-${arch}.dmg`

/** `sha256` is `{ arm64, x64 }`: the sha256 of Walnut-arm64.dmg and Walnut-x64.dmg. */
export function cask({ version, sha256, baseUrl = `${REPO_URL}/releases/download` }) {
  if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`${version} is not a stable version (x.y.z)`)
  for (const { arch } of DMG_ARCHES) {
    if (!/^[0-9a-f]{64}$/.test(sha256?.[arch] ?? '')) throw new Error(`${sha256?.[arch]} is not a sha256 (for ${dmgName(arch)})`)
  }
  return `# Generated by scripts/homebrew/cask.mjs in ${REPO_URL} for Walnut ${version}.
cask "walnut" do
  arch arm: "arm64", intel: "x64"

  version "${version}"
  sha256 arm:   "${sha256.arm64}",
         intel: "${sha256.x64}"

  url "${baseUrl}/v#{version}/Walnut-#{arch}.dmg"
  name "Walnut"
  desc "Personal AI: tasks, notes and Claude Code sessions on your own machine"
  homepage "${REPO_URL}"

  depends_on macos: :monterey

  app "Walnut.app"

  zap trash: [
    "~/Library/Application Support/Walnut",
    "~/Library/Caches/${BUNDLE_ID}",
    "~/Library/HTTPStorages/${BUNDLE_ID}",
    "~/Library/Preferences/${BUNDLE_ID}.plist",
    "~/Library/Saved Application State/${BUNDLE_ID}.savedState",
    "~/Library/WebKit/${BUNDLE_ID}",
  ]

  caveats <<~EOS
    The first launch sets Walnut up in ~/.local/share/open-walnut, from the copy the app
    carries; it keeps itself up to date from then on. Its sessions run Claude Code:
      https://claude.com/product/claude-code
  EOS
end
`
}

function main(argv) {
  const opts = { version: null, sha256: {}, baseUrl: undefined }
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--version') opts.version = argv[++i]
    else if (argv[i] === '--sha256-arm64') opts.sha256.arm64 = argv[++i]
    else if (argv[i] === '--sha256-x64') opts.sha256.x64 = argv[++i]
    else if (argv[i] === '--base-url') opts.baseUrl = argv[++i]
    else throw new Error(`unknown argument ${argv[i]}`)
  }
  if (!opts.version || !opts.sha256.arm64 || !opts.sha256.x64) throw new Error('usage: cask.mjs --version <x.y.z> --sha256-arm64 <sha of Walnut-arm64.dmg> --sha256-x64 <sha of Walnut-x64.dmg> [--base-url <url>]')
  process.stdout.write(cask(opts))
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main(process.argv.slice(2))
  } catch (err) {
    process.stderr.write(`cask: ${err instanceof Error ? err.message : String(err)}\n`)
    process.exit(1)
  }
}
