#!/usr/bin/env node
/**
 * The Homebrew formula for a release's self-contained archives
 * (.github/workflows/release-archives.yml attaches it to the release as
 * open-walnut.rb; the tap EvanZhang008/homebrew-tap mirrors the newest one):
 *
 *   brew install evanzhang008/tap/open-walnut
 *
 *   node scripts/homebrew/formula.mjs --version 0.6.3 --sums SHA256SUMS [--base-url <url>] > open-walnut.rb
 *
 * The archive goes into the keg still packed and is unpacked after install
 * (post_install_steps).
 * Homebrew rewrites the install name of every Mach-O file it finds in a keg it
 * built (Keg#fix_dynamic_linkage), and a prebuilt native module in the package
 * has no room in its header for the longer name (ripgrep.node: "Updated load
 * commands do not fit", and `brew install` fails). The post-install steps run after that
 * pass, and the archive needs no rewriting: every path in it is relative.
 * The formula carries no Node dependency: the archive runs on the Node inside
 * it and updates itself there (`walnut update`), so `brew upgrade` is only ever a
 * catch-up, never a requirement.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const REPO_URL = 'https://github.com/EvanZhang008/open-walnut'
/** Homebrew's words for each archive target, in the order the formula lists them. */
const TARGETS = [
  { target: 'darwin-arm64', os: 'on_macos', cpu: 'on_arm' },
  { target: 'darwin-x64', os: 'on_macos', cpu: 'on_intel' },
  { target: 'linux-arm64', os: 'on_linux', cpu: 'on_arm' },
  { target: 'linux-x64', os: 'on_linux', cpu: 'on_intel' },
]

/** `{ target: sha256 }` for one version's archives in a SHA256SUMS file. */
export function archivesIn(sums, version) {
  const out = {}
  for (const line of sums.split('\n')) {
    const m = /^([0-9a-f]{64}) [ *]?open-walnut-(.+)-((?:darwin|linux)-(?:arm64|x64))\.tar\.gz$/.exec(line.trim())
    if (m && m[2] === version) out[m[3]] = m[1]
  }
  return out
}

export function formula({ version, sums, baseUrl = `${REPO_URL}/releases/download` }) {
  // Releases are stable versions; CI's rehearsal writes one for a prerelease build.
  if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?$/.test(version)) throw new Error(`${version} is not a version`)
  const shas = archivesIn(sums, version)
  if (Object.keys(shas).length === 0) throw new Error(`SHA256SUMS lists no archive of ${version}`)
  const blocks = []
  for (const os of ['on_macos', 'on_linux']) {
    const inner = TARGETS.filter((t) => t.os === os && shas[t.target]).map((t) => [
      `    ${t.cpu} do`,
      `      url "${baseUrl}/v${version}/open-walnut-${version}-${t.target}.tar.gz", using: :nounzip`,
      `      sha256 "${shas[t.target]}"`,
      '    end',
    ].join('\n'))
    if (inner.length) blocks.push(`  ${os} do\n${inner.join('\n')}\n  end`)
  }
  return `# Generated by scripts/homebrew/formula.mjs in ${REPO_URL} for open-walnut ${version}.
class OpenWalnut < Formula
  desc "Personal AI: tasks, notes and Claude Code sessions on your own machine"
  homepage "${REPO_URL}"
  version "${version}"
  license "MIT"

${blocks.join('\n\n')}

  def install
    libexec.install Dir["open-walnut-*.tar.gz"].first => "open-walnut.tar.gz"
    # Scripts, not links: the cleaner drops a link whose target is not there yet.
    bin.write_exec_script libexec/"app/bin/walnut", libexec/"app/bin/open-walnut"
  end

  # After Homebrew's install-name pass over the keg, which the archive must skip.
  # The packed copy goes once unpacked, so running these again changes nothing.
  post_install_steps do
    if_path_exists "open-walnut.tar.gz", base: :libexec do
      remove "app", base: :libexec, recursive: true
      mkdir_p "app", base: :libexec
      run "tar", args: ["-xzf", "{{libexec}}/open-walnut.tar.gz", "-C", "{{libexec}}/app", "--strip-components=1"],
                 writable_paths: ["app"], writable_base: :libexec
      remove "open-walnut.tar.gz", base: :libexec
    end
  end

  def caveats
    <<~EOS
      Start it with:
        walnut web
      Walnut keeps itself up to date: it installs new releases when it starts.
      Its sessions run Claude Code: https://claude.com/product/claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/walnut --version")
  end
end
`
}

function main(argv) {
  const opts = { version: null, sums: null, baseUrl: undefined }
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--version') opts.version = argv[++i]
    else if (argv[i] === '--sums') opts.sums = argv[++i]
    else if (argv[i] === '--base-url') opts.baseUrl = argv[++i]
    else throw new Error(`unknown argument ${argv[i]}`)
  }
  if (!opts.version || !opts.sums) throw new Error('usage: formula.mjs --version <x.y.z> --sums <SHA256SUMS> [--base-url <url>]')
  process.stdout.write(formula({ version: opts.version, sums: fs.readFileSync(opts.sums, 'utf8'), baseUrl: opts.baseUrl }))
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main(process.argv.slice(2))
  } catch (err) {
    process.stderr.write(`formula: ${err instanceof Error ? err.message : String(err)}\n`)
    process.exit(1)
  }
}
