/**
 * Lane conversation auto-title (generateConversationTitle opts).
 *
 * A LANE conversation's transcript lives in the CLI's JSONL — chat-history is
 * empty — so the titler must accept a caller-fed transcript and a lower message
 * threshold, or lane tabs stay raw-text forever. Contract pinned here:
 *   - opts.transcript + minMessages:1 → LLM called with that transcript, title persisted
 *   - main conversation → never titled (even with opts)
 *   - titleAutoGenerated already set → skipped (one-shot)
 *   - default path (no opts) still requires MIN_MESSAGES (2) — lane opts don't
 *     loosen the ordinary chat-history path
 *
 * Real: conversations store on a temp WALNUT_HOME. Fake: the LLM (sendMessage).
 */
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { createMockConstants } from '../helpers/mock-constants.js';

vi.mock('../../src/constants.js', () => createMockConstants('walnut-lane-title'));

const sendMessageMock = vi.fn();
vi.mock('../../src/agent/model.js', () => ({
  sendMessage: (...args: unknown[]) => sendMessageMock(...args),
}));

import { generateConversationTitle } from '../../src/core/conversation-title.js';
import {
  createConversation, listConversations, getMainConversationId, touchLaneConversation,
} from '../../src/core/conversations.js';

const AGENT = 'general';

function llmReplies(title: string): void {
  sendMessageMock.mockResolvedValue({ content: [{ type: 'text', text: title }] });
}

describe('lane conversation auto-title', () => {
  beforeEach(() => {
    sendMessageMock.mockReset();
  });

  it('titles a lane conversation from a caller-fed transcript (minMessages 1)', async () => {
    llmReplies('Camping Trip');
    const conv = await createConversation(AGENT);
    // Simulate the lane send: metadata touch (messageCount 0→1, raw derive)…
    await touchLaneConversation(AGENT, conv.id, 'plan a weekend camping trip to Yosemite');
    // …then the titler with the fed transcript.
    const title = await generateConversationTitle(AGENT, conv.id, {
      transcript: 'User: plan a weekend camping trip to Yosemite',
      minMessages: 1,
    });
    expect(title).toBe('Camping Trip');
    const meta = (await listConversations(AGENT)).find((c) => c.id === conv.id);
    expect(meta?.title).toBe('Camping Trip');
    expect(meta?.titleAutoGenerated).toBe(true);
    // The fed transcript is what reached the LLM (not chat-history, which is empty).
    const call = sendMessageMock.mock.calls[0]![0] as { messages: Array<{ content: string }> };
    expect(call.messages[0]!.content).toContain('plan a weekend camping trip to Yosemite');
  });

  it('never titles the main conversation', async () => {
    llmReplies('Should Not Land');
    const mainId = await getMainConversationId(AGENT);
    const title = await generateConversationTitle(AGENT, mainId, {
      transcript: 'User: hello there, long enough text', minMessages: 1,
    });
    expect(title).toBeNull();
    expect(sendMessageMock).not.toHaveBeenCalled();
  });

  it('is one-shot: titleAutoGenerated blocks a second run', async () => {
    llmReplies('First Label');
    const conv = await createConversation(AGENT);
    await touchLaneConversation(AGENT, conv.id, 'first message about databases');
    await generateConversationTitle(AGENT, conv.id, {
      transcript: 'User: first message about databases', minMessages: 1,
    });
    sendMessageMock.mockClear();
    const again = await generateConversationTitle(AGENT, conv.id, {
      transcript: 'User: something entirely different', minMessages: 1,
    });
    expect(again).toBeNull();
    expect(sendMessageMock).not.toHaveBeenCalled();
  });

  it('default path still waits for two messages (lane opts do not loosen it)', async () => {
    llmReplies('Too Eager');
    const conv = await createConversation(AGENT);
    await touchLaneConversation(AGENT, conv.id, 'only one message so far');
    // No opts → chat-history path with MIN_MESSAGES=2; messageCount is 1 → skip.
    const title = await generateConversationTitle(AGENT, conv.id);
    expect(title).toBeNull();
    expect(sendMessageMock).not.toHaveBeenCalled();
  });
});
