/**
 * Conversation title summarizer.
 *
 * A conversation's tab label should be a short 2-5 word summary of what the
 * thread is about, generated AFTER there's been some chat (not the raw first
 * message, which is often a long paragraph). This mirrors fork-title.ts but for
 * conversation tabs.
 *
 * Design notes:
 * - Multilingual by intent. Unlike fork titles (English-only, externally synced),
 *   conversation titles are LOCAL display strings only, so we keep the user's
 *   language (Chinese chats get Chinese titles). No ASCII stripping.
 * - Uses a cheap, no-thinking Haiku-tier model — a trivial labeling task, not
 *   worth an Opus call. Falls back to the configured main model otherwise.
 * - Best-effort + idempotent: a module mutex bounds concurrent LLM calls, a
 *   per-conversation `titleAutoGenerated` flag prevents re-labeling, and every
 *   failure path is swallowed. NEVER throws into the chat flow.
 */

import { sendMessage } from '../agent/model.js';
import { log } from '../logging/index.js';
import { fastModelFor } from './cheap-model.js';
import { listConversations, renameConversation } from './conversations.js';
import { bus, EventNames } from './event-bus.js';
import * as chatHistory from './chat-history.js';

// 1-3 words; cap length as a belt-and-suspenders guard if the model over-produces.
const MAX_TITLE_LEN = 32;
// Generate once the thread has at least one full exchange worth summarizing.
const MIN_MESSAGES = 2;

// Module-level mutex: at most ONE title generation at a time (cost guard, mirrors distill).
let generating = false;

const TITLE_SYSTEM =
  'You name chat conversations. Given a conversation, reply with a very short ' +
  '1-3 word title capturing its core topic. Prefer fewer words. Reply with ONLY ' +
  'the title — no quotes, no punctuation, no trailing period, no preamble. Match ' +
  'the language the user is chatting in (e.g. a Chinese conversation gets a Chinese ' +
  'title). Examples: "Weekend Travel", "TypeScript Types", "报销流程".';

/** Normalize an LLM title: strip wrapping quotes, collapse whitespace, drop a trailing
 *  period, and cap length. Keeps non-ASCII (CJK titles are intended). */
export function normalizeTitle(raw: string): string {
  if (!raw) return '';
  let s = raw
    .replace(/["'`]/g, '')           // strip quotes the model may wrap around
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[.。!！?？]+$/, '')     // drop trailing sentence punctuation (ASCII + CJK)
    .trim();
  if (s.length > MAX_TITLE_LEN) s = s.slice(0, MAX_TITLE_LEN).trimEnd();
  return s;
}

/** Flatten display entries to a compact plain-text transcript for the title prompt. */
function entriesToTranscript(
  entries: import('./types.js').ChatEntry[],
  summary: string | null,
): string {
  const lines: string[] = [];
  if (summary) lines.push(`[Earlier summary] ${summary}`);
  for (const e of entries) {
    let text = '';
    if (typeof e.content === 'string') text = e.content;
    else if (e.tag === 'ai' && e.displayText) text = e.displayText;
    else if (Array.isArray(e.content)) {
      text = (e.content as Array<{ type: string; text?: string }>)
        .filter((b) => b.type === 'text' && b.text)
        .map((b) => b.text!)
        .join('');
    }
    text = text.trim();
    if (!text) continue;
    const who = e.role === 'assistant' ? 'Assistant' : 'User';
    lines.push(`${who}: ${text}`);
  }
  return lines.join('\n');
}

/**
 * Generate a 2-5 word title for a conversation and persist it. Returns the new
 * title, or null if skipped (already labeled / too short / mutex busy / failure).
 * Best-effort — never throws.
 *
 * `opts.transcript` feeds the summarizer directly instead of reading chat-history —
 * the LANE path needs this: a lane conversation's transcript lives in the CLI's
 * JSONL, so chat-history is empty and the default read would always bail. Lane
 * callers pass the user's message text (one message is plenty for a label, hence
 * `opts.minMessages: 1` there).
 */
export async function generateConversationTitle(
  agentId: string,
  conversationId: string,
  opts?: { transcript?: string; minMessages?: number },
): Promise<string | null> {
  // Cost guard: claim the mutex synchronously (no await between check + set).
  if (generating) return null;
  generating = true;
  try {
    const conversations = await listConversations(agentId);
    const meta = conversations.find((c) => c.id === conversationId);
    if (!meta) return null;

    // The main conversation is the agent's stable thread (notifications + cron); its
    // tab always reads "Main" in the UI, so never auto-title it.
    if (meta.isMain) return null;
    // Dedup: already auto-labeled, or user pinned/renamed it (titleAutoGenerated guards both).
    if (meta.titleAutoGenerated) return null;
    // Not enough conversation to summarize yet.
    if (meta.messageCount < (opts?.minMessages ?? MIN_MESSAGES)) return null;

    let transcript: string;
    if (opts?.transcript !== undefined) {
      transcript = opts.transcript;
    } else {
      const { messages: displayEntries } = await chatHistory.getDisplayEntries(
        1, Number.MAX_SAFE_INTEGER, agentId, conversationId,
      );
      const summary = await chatHistory.getCompactionSummary(agentId, conversationId);
      transcript = entriesToTranscript(displayEntries, summary);
    }
    if (transcript.length < 10) return null; // nothing meaningful

    const { getConfig } = await import('./config-manager.js');
    const config = await getConfig();
    const model = fastModelFor(config); // undefined → model.ts uses main_model

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 15_000);
    let result;
    try {
      result = await sendMessage({
        system: TITLE_SYSTEM,
        // Cap transcript so a huge thread doesn't blow the cheap model's window.
        messages: [{ role: 'user', content: `Conversation:\n${transcript.slice(0, 6000)}\n\nTitle:` }],
        // A title is a handful of tokens. Cap maxTokens hard: the catalog default
        // (64K) makes the non-streaming SDK path refuse the call ("Streaming is
        // required for operations that may take longer than 10 minutes").
        config: { ...(model ? { model } : {}), maxTokens: 256 },
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timer);
    }

    const text = (result.content ?? [])
      .map((b) => (b.type === 'text' && 'text' in b ? (b as { text: string }).text : ''))
      .join('')
      .trim();
    const title = normalizeTitle(text);
    if (!title) return null;

    // Persist + mark so we don't regenerate. `auto: true` sets titleAutoGenerated.
    await renameConversation(agentId, conversationId, title, { auto: true });
    // Notify the UI (server.ts 'web-ui' bus subscriber bridges this to WS clients).
    const updated = (await listConversations(agentId)).find((c) => c.id === conversationId);
    if (updated) {
      bus.emit(EventNames.CONVERSATION_UPDATED, { agentId, conversation: updated }, ['web-ui'], {
        source: 'conversation-title',
      });
    }
    log.agent.info('conversation auto-titled', { agentId, conversationId, title });
    return title;
  } catch (err) {
    log.agent.debug('conversation title generation failed (non-critical)', {
      agentId, conversationId, error: err instanceof Error ? err.message : String(err),
    });
    return null;
  } finally {
    generating = false;
  }
}
